### ISSUE TITLE
Environments support (deployment.environment = staging/production)

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/roadmap#11]
**Goal**. Allow having data from multiple environments in the same project.
**Caveat**. Don't end up replicating all the features for environments, i.e. having a project (environment) within a project. Projects still should be the main way to separate data. Environments should help closing some corner cases and be as light as possible.

Uptrace should use `deployment.environment` for:
- [x] Grouping. Spans from different environments must end up in different groups, e.g. one group from environment `staging` and another group from `production`.
- [ ] Notifications. It should be possible to configure notifications separately for each environment.

**Comment by schmurfy** [comment]
Another, maybe easier, solution to out problem would be to be able to filter the data used in the list of services, systems, alerts. for alerts I imagine it could be harder since the data are most likely precomputed.

**Comment by vmihailenco** [comment]
We will be adding some filtering capabilities to alerts - at least by system & service name. I just feel we need to make alerts more useful & stable first :)

As for the services & systems I don't want to complicate those views, but I am going to add links to spans explorer with equivalent functionality. Should not take more than few days.

**Comment by vmihailenco** [comment]
Just added an env filter for tracing:

![env-filter](https://user-images.githubusercontent.com/290976/194705973-f325fc20-aa22-45a1-b6e0-a18ce5be5110.png)

It should appear automatically when you have 2 or more environments.
