### ISSUE TITLE
Improve existing and add more Uptrace clients (Go, JS, Python etc)

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/roadmap#4]
This also includes docs and instrumentations

- [x] Go
- [x] JS
- [x] Python
- [x] Ruby
- [ ] Java
- [x] .NET

**Comment by faceair** [comment]
Hi @vmihailenco , the [uptrace-java](https://github.com/uptrace/uptrace-java) repository seems to be still empty, when will it be released?

**Comment by vmihailenco** [comment]
@faceair I am not sure. It **looks** like Java has true auto-instrumentation that is actually working. You can instrument Java projects without installing any libraries / code, for example, https://blog.uptrace.dev/posts/opentelemetry-java-spring-boot-auto-instrumentation.html

So the question is whether we need to provide uptrace-java or encourage users to use auto-instrumentation? Do you have any experience with this?

**Comment by faceair** [comment]
I'm sorry, I'm not good at Java either, I'm just curious about the task being closed but not seeing the code.

**Comment by vmihailenco** [comment]
With Java we are going to try the agent - see https://docs.uptrace.dev/guide/java.html#getting-started
